package constant

object UserConstants {

    val emailDomains = listOf(
        "gmail.com",
        "yahoo.com",
        "hotmail.com",
        "outlook.com",
        "icloud.com",
        "protonmail.com"
    )

    val firstNames = listOf(
        "John",
        "Jane",
        "Alice",
        "Bob",
        "Charlie",
        "David",
        "Eve",
        "Frank",
        "Grace",
        "Helen",
        "Ivy",
        "Jack",
        "Kate",
        "Liam",
        "Mia",
        "Noah",
        "Olivia",
        "Peter",
        "Quinn",
        "Ryan",
        "Sophia",
        "Tom",
        "Ursula",
        "Victor",
        "Wendy",
        "Xander",
        "Yvonne",
        "Zack"
    )

    val interests = listOf(
        "Art",
        "Books",
        "Cinema",
        "Cooking",
        "Dancing",
        "Fishing",
        "Gaming",
        "Hiking",
        "Music",
        "Photography",
        "Programming",
        "Sports",
        "Traveling",
        "Writing"
    )

    val lastNames = listOf(
        "Smith",
        "Johnson",
        "Williams",
        "Jones",
        "Brown",
        "Davis",
        "Miller",
        "Wilson",
        "Moore",
        "Taylor",
        "Anderson",
        "Thomas",
        "Jackson",
        "White",
        "Harris",
        "Martin",
        "Thompson",
        "Garcia",
        "Martinez",
        "Robinson",
        "Clark",
        "Rodriguez",
        "Lewis",
        "Lee",
        "Walker",
        "Hall",
        "Allen",
        "Young",
        "Hernandez",
        "King",
        "Wright",
        "Lopez",
        "Hill",
        "Scott",
        "Green",
        "Adams",
        "Baker",
        "Gonzalez",
        "Nelson",
        "Carter",
        "Mitchell",
        "Perez",
        "Roberts",
        "Turner",
        "Phillips",
        "Campbell",
        "Parker",
        "Evans",
        "Edwards",
        "Collins",
        "Stewart",
        "Sanchez",
        "Morris",
        "Rogers",
        "Reed",
        "Cook",
        "Morgan",
        "Bell",
        "Murphy",
        "Bailey",
        "Rivera",
        "Cooper",
        "Richardson",
        "Cox",
        "Howard",
        "Ward",
        "Torres",
        "Peterson",
        "Gray",
        "Ramirez",
        "James",
        "Watson",
        "Brooks",
        "Kelly",
        "Sanders",
        "Price",
        "Bennett",
        "Wood",
        "Barnes",
        "Ross",
        "Henderson",
        "Coleman",
        "Jenkins",
        "Perry",
        "Powell",
        "Long",
        "Patterson",
        "Hughes",
        "Flores",
        "Washington",
        "Butler",
        "Simmons",
        "Foster",
        "Gonzales",
        "Bryant",
        "Alexander",
        "Russell",
        "Griffin",
        "Diaz",
        "Hayes"
    )

    val locations = listOf(
        "Lithuania/Vilnius",
        "Lithuania/Kaunas",
        "Lithuania/Klaipėda",
        "Latvia/Riga",
        "Latvia/Daugavpils",
        "Japan/Tokyo",
        "Japan/Yokohama",
        "Japan/Osaka",
        "China/Shanghai",
        "China/Beijing",
        "Canada/Toronto",
        "Canada/Montreal",
        "Canada/Vancouver",
        "United States/New York",
        "United States/Los Angeles",
        "United States/Chicago",
        "United States/Houston",
        "United States/Phoenix",
        "France/Paris",
        "France/Marseille",
        "Italy/Rome",
        "Italy/Milan",
        "Italy/Naples",
        "Spain/Madrid",
        "Spain/Barcelona",
        "Germany/Berlin",
        "Germany/Hamburg",
        "Luxembourg/Luxembourg",
        "United Kingdom/London",
        "United Kingdom/Birmingham",
        "United Kingdom/Liverpool",
        "Russia/Moscow",
        "Russia/Saint Petersburg",
        "Ukraine/Kyiv",
        "Ukraine/Kharkiv",
        "Ukraine/Odesa",
        "Chech Republic/Prague",
        "Slovakia/Bratislava",
        "Poland/Warsaw",
        "Poland/Kraków",
        "Portugal/Lisbon",
        "Portugal/Porto"
    ).shuffled()

    val statuses = listOf(
        "Active",
        "Away",
        "Busy",
        "Invisible"
    )
}