[versions]
apache-commons = "3.17.0"
guava = "33.3.1-jre"
koin = "4.0.0"
kotlin-version = "2.0.21"
ktor-version = "3.0.0"
logback-version = "1.4.14"
moshi = "1.15.1"
neo4j-driver = "5.25.0"
typesafe-config = "1.4.3"

[libraries]
apache-commons = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-version" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor-version" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
neo4j-driver = { module = "org.neo4j.driver:neo4j-java-driver", version.ref = "neo4j-driver" }
typesafe-config = { module = "com.typesafe:config", version.ref = "typesafe-config" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }